LEADS = [
    {
        "id": "L001",
        "name": "Priya Sharma",
        "title": "VP of Sales",
        "company": "TechNova India",
        "industry": "SaaS",
        "employees": 320,
        "revenue_usd": 12000000,
        "linkedin_url": "https://linkedin.com/in/priya-sharma",
        "email": "priya@technova.in",
        "last_activity": "2025-03-20",
        "intent_signals": ["visited pricing page", "downloaded ROI calculator"],
        "lead_score": None,
        "outreach_email": None,
    },
    {
        "id": "L002",
        "name": "Amit Verma",
        "title": "CTO",
        "company": "FinEdge Solutions",
        "industry": "Fintech",
        "employees": 150,
        "revenue_usd": 5000000,
        "linkedin_url": "https://linkedin.com/in/amit-verma",
        "email": "amit@finedge.io",
        "last_activity": "2025-03-18",
        "intent_signals": ["competitor comparison search", "webinar attended"],
        "lead_score": None,
        "outreach_email": None,
    },
    {
        "id": "L003",
        "name": "Sarah Mitchell",
        "title": "Director of Revenue Operations",
        "company": "GrowthLoop US",
        "industry": "MarTech",
        "employees": 85,
        "revenue_usd": 8000000,
        "linkedin_url": "https://linkedin.com/in/sarah-mitchell",
        "email": "sarah@growthloop.com",
        "last_activity": "2025-03-22",
        "intent_signals": ["demo request", "visited case studies"],
        "lead_score": None,
        "outreach_email": None,
    },
    {
        "id": "L004",
        "name": "Rajesh Kumar",
        "title": "Head of Operations",
        "company": "LogiFlow India",
        "industry": "Logistics",
        "employees": 600,
        "revenue_usd": 25000000,
        "linkedin_url": "https://linkedin.com/in/rajesh-kumar",
        "email": "rajesh@logiflow.in",
        "last_activity": "2025-03-10",
        "intent_signals": ["email opened 3x", "pricing page visit"],
        "lead_score": None,
        "outreach_email": None,
    },
    {
        "id": "L005",
        "name": "Emily Chen",
        "title": "Chief Revenue Officer",
        "company": "CloudScale AI",
        "industry": "AI/ML",
        "employees": 210,
        "revenue_usd": 18000000,
        "linkedin_url": "https://linkedin.com/in/emily-chen",
        "email": "emily@cloudscale.ai",
        "last_activity": "2025-03-24",
        "intent_signals": ["booked demo", "referral from partner"],
        "lead_score": None,
        "outreach_email": None,
    },
]

DEALS = [
    {
        "id": "D001",
        "lead_id": "L003",
        "name": "GrowthLoop - Enterprise License",
        "stage": "Negotiation",
        "value": 120000,
        "currency": "USD",
        "close_date": "2025-04-15",
        "days_in_stage": 18,
        "last_reply_days_ago": 9,
        "email_thread_id": "T001",
        "risk_score": None,
        "risk_reasons": [],
        "recovery_actions": [],
    },
    {
        "id": "D002",
        "lead_id": "L001",
        "name": "TechNova - Sales Automation Suite",
        "stage": "Proposal Sent",
        "value": 75000,
        "currency": "USD",
        "close_date": "2025-04-30",
        "days_in_stage": 7,
        "last_reply_days_ago": 2,
        "email_thread_id": "T002",
        "risk_score": None,
        "risk_reasons": [],
        "recovery_actions": [],
    },
    {
        "id": "D003",
        "lead_id": "L002",
        "name": "FinEdge - RevOps Platform",
        "stage": "Discovery",
        "value": 48000,
        "currency": "USD",
        "close_date": "2025-05-10",
        "days_in_stage": 3,
        "last_reply_days_ago": 1,
        "email_thread_id": "T003",
        "risk_score": None,
        "risk_reasons": [],
        "recovery_actions": [],
    },
    {
        "id": "D004",
        "lead_id": "L004",
        "name": "LogiFlow - Operations Intelligence",
        "stage": "Negotiation",
        "value": 200000,
        "currency": "USD",
        "close_date": "2025-04-05",
        "days_in_stage": 25,
        "last_reply_days_ago": 14,
        "email_thread_id": "T001",
        "risk_score": None,
        "risk_reasons": [],
        "recovery_actions": [],
    },
    {
        "id": "D005",
        "lead_id": "L005",
        "name": "CloudScale AI - Partnership Deal",
        "stage": "Proposal Sent",
        "value": 90000,
        "currency": "USD",
        "close_date": "2025-04-20",
        "days_in_stage": 5,
        "last_reply_days_ago": 1,
        "email_thread_id": "T002",
        "risk_score": None,
        "risk_reasons": [],
        "recovery_actions": [],
    },
]

EMAIL_THREADS = [
    {
        "id": "T001",
        "subject": "Re: LogiFlow - Operations Intelligence Proposal",
        "messages": [
            {"from": "ae@revagent.ai", "date": "2025-03-01", "body": "Hi Rajesh, excited to share our proposal for LogiFlow. We believe RevAgent can reduce your ops costs by 30%."},
            {"from": "rajesh@logiflow.in", "date": "2025-03-03", "body": "Thanks. We are evaluating two other vendors as well. Can you do better on price?"},
            {"from": "ae@revagent.ai", "date": "2025-03-05", "body": "Absolutely, I can offer a 10% discount and priority onboarding. Let me know if you'd like a deeper demo."},
            {"from": "rajesh@logiflow.in", "date": "2025-03-10", "body": "We'll circle back after our board meeting next week."},
        ],
        "sentiment": "cautious",
        "competitor_mentions": ["Salesforce", "HubSpot"],
    },
    {
        "id": "T002",
        "subject": "Re: RevAgent Demo Follow-up",
        "messages": [
            {"from": "ae@revagent.ai", "date": "2025-03-15", "body": "Hi Priya, great connecting today! Sharing our deck and ROI model as discussed."},
            {"from": "priya@technova.in", "date": "2025-03-16", "body": "Loved the demo! The AI email feature is exactly what we need. Sharing with my team."},
            {"from": "ae@revagent.ai", "date": "2025-03-18", "body": "Wonderful! Happy to set up a technical deep-dive with your team anytime."},
        ],
        "sentiment": "positive",
        "competitor_mentions": [],
    },
    {
        "id": "T003",
        "subject": "FinEdge Discovery Call Notes",
        "messages": [
            {"from": "ae@revagent.ai", "date": "2025-03-20", "body": "Hi Amit, great call today. Attaching our discovery notes and next steps."},
            {"from": "amit@finedge.io", "date": "2025-03-21", "body": "Thanks. One concern - how does your platform handle compliance for fintech? We saw Gong has a fintech add-on."},
        ],
        "sentiment": "neutral",
        "competitor_mentions": ["Gong"],
    },
]

COMPETITOR_SIGNALS = [
    {
        "id": "C001",
        "competitor": "Salesforce",
        "headline": "Salesforce launches AI-powered RevOps suite at 40% lower price",
        "source": "TechCrunch",
        "date": "2025-03-22",
        "impact": "high",
        "affected_deals": ["D001", "D004"],
    },
    {
        "id": "C002",
        "competitor": "Gong",
        "headline": "Gong raises $200M, announces fintech vertical product",
        "source": "Forbes",
        "date": "2025-03-21",
        "impact": "medium",
        "affected_deals": ["D003"],
    },
]

CHURN_SIGNALS = [
    {
        "account_id": "ACC001",
        "company": "OldClient Corp",
        "usage_drop_pct": 62,
        "support_tickets": 5,
        "nps_score": 22,
        "last_login_days_ago": 18,
        "sentiment": "negative",
        "contract_renewal_days": 45,
    }
]
